### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by jonasled** [sourcechord/FluentWPF#100]
The last commit was almost one year ago, so I wanted to ask if this project is dead?

**Comment by sourcechord** [comment]
Hi, @jonasled.
For a long time, I hadn't been able to spend the time to development.
I am sorry to worry you.
I'll continue to develop this project.

To start with, I'll merge some PR's and release it in few weeks.
Please wait for a while.

**Comment by Armin2208** [comment]
welcome back <3
