### ISSUE TITLE
Dual monitor - Maximized window showing blured edge on second screen

### ISSUE THREAD

**Issue by milos12345** [sourcechord/FluentWPF#101]
If I run the example project showing AcylicWindow and maximize it on one display, a blur will appear on the edge of the second screen.

![image](https://user-images.githubusercontent.com/5231547/109046226-80a4de00-76a2-11eb-8273-e7ceecbc7df5.png)

Is it possible to prevent this?

**Comment by sourcechord** [comment]
Hi @milos12345.

Thanks for the feedback.
This is same to #36.

So that, I'll close this issue and track with #36.
