### ISSUE TITLE
App crash with Hardcodet NotifyIcon ContextMenu

### ISSUE THREAD

**Issue by IllyaTheHath** [sourcechord/FluentWPF#107]
In my situation, I start my app as a tray icon, and use ContextMenu to open MainWindow, but it will crash when menu shows.

**Comment by IllyaTheHath** [comment]
I made some test, and found out it crash at ThemeHandler.cs, line 32.

If there is no MainWindow show, just a tray icon with contextmenu, when the menu shown, the Application.Current.MainWindow will return null so it crashed.
I added some code to determine whether MainWindow it is null and seems everything works fine.

**Comment by sourcechord** [comment]
Hi @IllyaTheHath 
Thanks for the feedback, and sorry for responding so late.
I checked your PR, but it has side effect for AccentColors and theme resources. FluentWPF follows the change of system settings in Windows. 
If skip the initializations, the window will not follows the changes of system settings.
https://github.com/sourcechord/FluentWPF/pull/109/files#diff-1297bb28e3738fc67e5828e370a749202d90f0553c8f219758e3d8d29d86427bR34-R38

However, I understand the bug that you reported, and I'm trying to fix it.
