### ISSUE TITLE
Enhancement: Increase the intensity of the Blur

### ISSUE THREAD

**Issue by shannonfonseka** [sourcechord/FluentWPF#112]
Is there a way I can increase the blur intensity? Below is an image on how it looks like on the application I'm making...
> ![image](https://user-images.githubusercontent.com/58655133/122670902-e97c0d00-d1e1-11eb-996f-e2dfdefc1ac1.png)

I want my application to look like this, the image below (from Groove Music)
> ![image](https://user-images.githubusercontent.com/58655133/122670897-e5e88600-d1e1-11eb-8a08-5b39d91d2e84.png)

Changing the blur intensity programmatically is also fine :)
This project is amazing by the way.

**Comment by sourcechord** [comment]
Hi @shannonfonseka 
Thanks for the feedback.
This is same to #42, and I fixed it in FluentWPF 0.10.0-alpha1. FluentWPF 0.10.0 has hard blur effect that is same as UWP apps.
I'll release FluentWPF0.10.0 in a few days. Please wait for a while.
