### ISSUE TITLE
It seems that AcrylicMessageBox is missed in Nuget package! 

### ISSUE THREAD

**Issue by TMS-Namespace** [sourcechord/FluentWPF#117]
Was trying to implement this class from latest Nuget,  but VS couldn't resolve its name (although it resolved the rest acrylic classes),  so I assume it is private or just dropped from it. 

Of course I ended up in using the source code directly that contains it and working fine. 

And thanks for the great work  ;)

**Comment by sourcechord** [comment]
Hi @TMS-Namespace 
AcrylicMessageBox is currently preview state, that is only included in preview package.
[FluentWPF 0.10.0-alpha001](https://www.nuget.org/packages/FluentWPF/0.10.0-alpha001)

I'll release AcrylicMessageBox with stable FluentWPF 0.10.0 packages. Please wait for a while

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
