### ISSUE TITLE
Attached AcrylicWindow dose not work within setters when in ResourceDictionary! 

### ISSUE THREAD

**Issue by TMS-Namespace** [sourcechord/FluentWPF#118]
I believe the title is self explanatory.. 

Tried it multiple times..  Once moved to the window it self, everything is fine. 

`<Setter Property="fw:AcrylicWindow.Enabled" Value="True" />`

**Comment by sourcechord** [comment]
Hi @TMS-Namespace 
Thanks for the feedback.
I'll fix it in next release.
