### ISSUE TITLE
[Bug] The minimize and maximize animation does not work

### ISSUE THREAD

**Issue by ORRNY66** [sourcechord/FluentWPF#119]
Hi, I like your work but I came across a few bugs in the latest pre-release 0.10.0-alpha001. In the previous version it works well. v0.9.0
1) Window minimization or maximization animation does not work
2) if I set AcrylicAccentState to disable, a gray border will appear when the window is maximized

https://user-images.githubusercontent.com/5471789/126295331-9dec8fe1-1197-4e91-ae69-ea4fc35a7b86.mp4

https://user-images.githubusercontent.com/5471789/126295560-4ad50cd9-1af6-4b6c-bb1c-58cde5aa5591.mp4

![image](https://user-images.githubusercontent.com/5471789/126308794-ef59d465-e2fd-425c-97fb-07a1264f4a0a.PNG)

**Comment by sourcechord** [comment]
Thanks for the feedback. I can reproduce it, and I'm trying to fix it.
