### ISSUE TITLE
[Question/Bug] Dark theme TextBlock doesn't work very well inside a Frame

### ISSUE THREAD

**Issue by noobhacker** [sourcechord/FluentWPF#120]
Hi, 

I love your work and I have a weird issue with dark theme.

![image](https://user-images.githubusercontent.com/16358189/126368582-0d5b898a-9d25-4e23-856d-511a7891c504.png)

The controls on the left are directly on AcrylicWindow and they work very well. However, the TextBlock on the right is inside a Page hosted by a Frame. It remains in black color until I change some settings (Dark/Light theme or transparency effects) in Windows Settings. 
![image](https://user-images.githubusercontent.com/16358189/126370201-cfe804ae-41b4-4f02-8b75-9dc425a824de.png)
Sometimes clicking on the start button in Windows explorer will trigger the TextBlock into white color as well.

I turn the transparency effects in settings off and on then it works as usual. However, upon the app restart, it remains in black.
![image](https://user-images.githubusercontent.com/16358189/126369192-638e29c4-a032-4766-a923-5f6868e10a86.png)

The button behaves normally all time even inside a Page hosted by a Frame.

Does anyone here have remedy for this? This happens in 0.10.0-alpha001 and Nuget v0.9.0 as well. Thanks!
My source code is here:
https://github.com/noobhacker/FluentWPF.Shell

**Comment by sourcechord** [comment]
Thanks for the feedback. I could reproduce it, and fixed it.
It will included in FluentWPF 0.10.0.
