### ISSUE TITLE
[Bug] dpiAware is true/mp causes the application to move incorrectly. 

### ISSUE THREAD

**Issue by ORRNY66** [sourcechord/FluentWPF#121]
Hi, so I found another mistake. When I set the dpiAware node to true / mp in the manifest file, see the blog [blog.walterlv.com](https://www.programmersought.com/article/859498060/) This causes the application to move incorrectly when the application window is maximized, see the video below. I need to set the dpiAware node to true / mp because the value set to only true causes blur at 150% magnification. see pictures below.

https://user-images.githubusercontent.com/5471789/126481008-60acc97e-d074-4eaf-a46e-a27d349e341e.mp4

dpiAwareness Not set, **dpiAware** Node is set to **true**
**▼ 150% DPI**

<img width="377" alt="img" src="https://user-images.githubusercontent.com/5471789/126480017-f0332c90-6f10-475a-820e-a2313a2d47ab.PNG">

dpiAwareness Not set, **dpiAware** Node is set to **true/pm：**
**▼ 150% DPI**

<img width="415" alt="img1" src="https://user-images.githubusercontent.com/5471789/126480174-2cab2b5f-88b9-4942-9992-2d76bb570073.PNG">

**Comment by sourcechord** [comment]
Hi, @ORRNY66 
Thanks for the feedback.
I was able to reproduce it, and trying to fix it.
