### ISSUE TITLE
About TintLuminosityOpacity

### ISSUE THREAD

**Issue by LiMei1998** [sourcechord/FluentWPF#122]
Hello, thank you for your work, it is pretty good, I can create a nice WPF project by it when UWP Acrylic does not work well in WPF project.
As we kown, there is a property called 'TintLuminosityOpacity' in the Acrylic when we use WinUI 3 Controls Gallery, it seems that is not the same as 'TintOpacity'. Have you ever learn about it?

**Comment by sourcechord** [comment]
Hi @LiMei1998 
Thanks for the feedback.
But FluentWPF doesn't use WinUI 3. FluentWPF is implemented by `SetWindowCompositionAttribute` API, and that API doesn't provide `TintLuminosityOpacity`.
So that, It is no planed to add `TintLuminosityOpacity` in FluentWPF.

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
