### ISSUE TITLE
ComboBox Itemsource

### ISSUE THREAD

**Issue by farhadala** [sourcechord/FluentWPF#123]
When use ComboboxRevealStyle, display member path is not show in comboBox popup.
![Untitled](https://user-images.githubusercontent.com/16700672/126860666-b8e3657e-2ed3-46f3-bbcb-4b806f64e541.png)

**Comment by sourcechord** [comment]
Thanks for the feedback. I could reproduce it, and fixed it.
It will included in FluentWPF 0.10.0.
