### ISSUE TITLE
After move the Blur effects turns off in 0.10.0-alpha001

### ISSUE THREAD

**Issue by milos12345** [sourcechord/FluentWPF#128]
Once the window move is complete the blur effect turns off.

![OnReleaseRemovedAcrylicEffect](https://user-images.githubusercontent.com/5231547/127782068-cd300340-3dac-43a6-b04f-d1121be52f62.gif)

Win 10 20H2 (19042.1110)
RTX 2080

**Comment by sourcechord** [comment]
Hi @milos12345 
Currently Windows11 seems that doesn't support acrylic effect with SetWindowCompositionAttribute API. So that,  I turnd off acrylic effect in FluentWPF 0.10.0.  
See also(#130, [#42](https://github.com/sourcechord/FluentWPF/issues/42#issuecomment-891954225))

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
