### ISSUE TITLE
Draggable area still overlaying content when setting ExtendViewIntoTitleBar="True"

### ISSUE THREAD

**Issue by marcpabst** [sourcechord/FluentWPF#13]
Hi,

when using  ExtendViewIntoTitleBar="True" the titlebar will still act as a drag area even though content is now extending into it. Is there any way to display content above this are?

**Comment by sourcechord** [comment]
Hi, @marcpabst.
Thanks for the feedback.
And sorry for very late reply.

I'm trying to add a titlebar custumization feature like the link below.
https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#draggable-regions

And I'd like to release it in the next update.
Please wait for a while.

**Comment by HelgeKeck** [comment]
just add WindowChrome.IsHitTestVisibleInChrome="True" to your Control and it works

**Comment by TheSubGenius** [comment]
> just add WindowChrome.IsHitTestVisibleInChrome="True" to your Control and it works

Worked, thanks.
