### ISSUE TITLE
AcrylicWindow ignores Min/Max Height/Width

### ISSUE THREAD

**Issue by TMS-Namespace** [sourcechord/FluentWPF#132]
It seems that putting this restrictions has no effect when using AcrylicWindow.

Tried that even with the provided .Net core sample,  and also those settings are just ignored. 

(This was true for previous alpha and current stable).

**Comment by fhnb16** [comment]
Confirm this issue, FluentWPF 0.10.0

**Comment by josepho0918** [comment]
Same issue here.

**Comment by josepho0918** [comment]
Min Height/Width still doesn't work in FluentWPF 0.10.1

**Comment by fhnb16** [comment]
True, not fixed in 0.10.1(

**Comment by sourcechord** [comment]
Hi there.
Thanks for the information.

I fixed only MaxWidth/MaxHeight in this issue, and couldn't fix MinWidth/MinHeight.
BTW, there are similar report in #140.I'll track it with above issue.
