### ISSUE TITLE
Segoe MDL2 Assets are unavailable on win7 or 8

### ISSUE THREAD

**Issue by SlackingVeteran** [sourcechord/FluentWPF#135]
[According to Microsoft Segoe MDL2 Assets are only available on windows 10 devices unless users install them manually on other OS](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font)

I was testing my app on windows 7 VM and noticed dropdown arrow used in ComboBox is not displayed properly. Had to check ComboBox.xaml file to find out Segoe MDL2 Assets font family was used for DropDownGlyph. Can we replace it so that its compatible with older OS as well?

![image](https://user-images.githubusercontent.com/5356702/131211795-086a4c1a-375f-4a19-8ed0-317220f15791.png)
![image](https://user-images.githubusercontent.com/5356702/131211815-ebfee9ce-65a6-41c8-aa40-0adc0872ece7.png)

**Comment by Extrimis** [comment]
You can pack mdl assets along with fluent wpf if you need. This one is the
best example :https://stackoverflow.com/a/39912794/12427812

**Comment by sourcechord** [comment]
@SlackingVeteran 
Thanks for the feedback.
I'd like to remove the dependency for MDL2 Assets font. And, I'll fix it in next release.

**Comment by SlackingVeteran** [comment]
Thanks, i’d be greatly appreciated!

Would you mind linking commit to this issue when you do so? I had to modify
few things in fluentWPF and I use it in a unreleased app. I think I cloned
FluentWPF few version back and few things are outdated. If you link the
commit, i could just apply changes manually

**Comment by SlackingVeteran** [comment]
Awesome, thanks!
