### ISSUE TITLE
Tab issue with FluentWPF:Window

### ISSUE THREAD

**Issue by SlackingVeteran** [sourcechord/FluentWPF#137]
When fw:AcrylicWindow is used, it tabbing through controls break. After reaching to last control, it takes additional 4 tabs to reach the 1st control. Seems like 3 tabs entries are focusing or highlighting something thats not visible? Probably due to some isTabStop? I have added video to show the difference between Window and fw:AcrylicWindow and how its affecting

https://user-images.githubusercontent.com/5356702/134038171-06f48a48-7567-445e-abfd-7c2838b7a56c.mp4

**Comment by SlackingVeteran** [comment]
Out of 3 tabs that didn't select anything I was able to remove 1 by adding `isTabStop="False"` to [ContentControl in Window.xaml](https://github.com/sourcechord/FluentWPF/blob/afc4966df38c50c24d3da963d39a502921259318/FluentWPF/Styles/Window.xaml#L239) Still trying to see where else it needs to be added

**Comment by sourcechord** [comment]
Hi, @SlackingVeteran 
Thanks for the information. I'll review it later 😃

**Comment by SlackingVeteran** [comment]
Fixed by #138
