### ISSUE TITLE
AcrylicWindow doesn't respect MinHeight and MinWidth

### ISSUE THREAD

**Issue by Armin2208** [sourcechord/FluentWPF#140]
This bug was introduced in FluentWPF 10.1.
After downgrading to FluentWPF 10.0 it works again as expected.

Following values are set for the AcrylicWindow:
        MinHeight="700"
        MinWidth="820" 

Behavior:
The user can still resize the window below the declared value. The colorful 1px window border & window content doesn't respond to the resize below MinHeight and MinWidth value.

**Comment by sourcechord** [comment]
Hi @Armin2208 
Thanks for the feedback.
I'll fix this issue in the next update.

**Comment by RickyYChan** [comment]
Same. But the problem will appear in 0.10+(0.10.1 and 0.10.0 are both included), which works well in 0.9.
