### ISSUE TITLE
Acrylic window is too pixelated

### ISSUE THREAD

**Issue by Pietro228** [sourcechord/FluentWPF#151]
Hi,

why is my window pixelated? Iˇm using windows 11 and version 0.9.

![obrazek](https://user-images.githubusercontent.com/53868994/141655688-67b5ade9-39c5-4ed3-8ce4-e104370db967.png)

**Comment by Spiritreader** [comment]
Ít's not really pixelation, but more a noise effect that is applied to all windows to varying degrees.

You should be able to modify that by adjusting the `NoiseOpacity` property either in XAML or programmatically.
![image](https://user-images.githubusercontent.com/18438899/141861070-0f77c358-a7e7-4467-a99a-723a7e99a51a.png)

**Comment by Pietro228** [comment]
I have already tried to change it's value, but it only disables blur or makes it so much pixelated. Which value should I use to get rid of pixelated noise?

**Comment by Pietro228** [comment]
Fixed it with value 0! :)

**Comment by Pietro228** [comment]
Fixed it with value 0! :)
