### ISSUE TITLE
The hoverlight of UI elements should be shown immediately

### ISSUE THREAD

**Issue by tobiichiamane** [sourcechord/FluentWPF#16]
When hovering over an element that supports Reveal Effect, the highlight color shows up gradually as an animation (Duration="0:0:0.600"), but considering that in UWP applications, the default Reveal Effect actually shows the highlight color of an element immediately when hovering over an element, I think the duration of the opacity animation of "backgroundBorder"  triggered by hovering over should be set to 0.

**Comment by sourcechord** [comment]
Hi, @TobiichiAmane.

Sorry for replying so very very late.
Thanks for your feedback.
UWP's reveal effect is still updating, and I'll try to follow it.
I'm now updating these effect.

Thanks.

**Comment by tobiichiamane** [comment]
No problem. Thanks for this high-quality project.

**Comment by sourcechord** [comment]
Thanks.
I'll close this issue.
If you have any problems, please reopen this issue.
