### ISSUE TITLE
Icon at the left of the window title

### ISSUE THREAD

**Issue by Stryxus** [sourcechord/FluentWPF#22]
Since this is a traditional thing and some people would want to do this anyway. Why not?

**Comment by sourcechord** [comment]
Hi, @Stryxus.
Thanks for the feedback.
And sorry for responding so late.

I think so too, and recognized that these feature is necessary in some scenes.
I'll add this feature in the next update.

**Comment by sourcechord** [comment]
@Stryxus

I released FluentWPF 0.7.0.
There is new AcrylicWindow style, that has application icon.
Please try it.

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
