### ISSUE TITLE
Some theme change detection?

### ISSUE THREAD

**Issue by Epat9** [sourcechord/FluentWPF#23]
Is there any event or something similar that indicates change of Windows 10 dark/light mode?

**Comment by sourcechord** [comment]
Hi, @Epat9.

Sorry for replying so late.
There is `SystemTheme.ThemeChanged` event for detect system theme changed.

You can detect it by the code below.

```cs

    public partial class App : Application
    {
        public App()
        {
            SourceChord.FluentWPF.SystemTheme.ThemeChanged += this.SystemTheme_ThemeChanged;
        }

        private void SystemTheme_ThemeChanged(object sender, EventArgs e)
        {
            MessageBox.Show("Changed!");
        }
    }
```

Please, try it.
