### ISSUE TITLE
Control buttons not displaying on windows 7

### ISSUE THREAD

**Issue by fangeles02** [sourcechord/FluentWPF#26]
Hi, the control buttons for non-windows 10 are not displaying correctly. Please see the attached image.
![fluentwpf win7](https://user-images.githubusercontent.com/26376969/46925380-2a4d1c80-d05e-11e8-84a7-200c06ba324b.PNG)

**Comment by sourcechord** [comment]
Hi, @fangeles02.

I recognized this issue.
FluentWPF uses "Segoe MDL2 Assets" font for draw AcrylicWindow's title bar buttons.
But, Windows7, 8.x doesn't have Segoe MDL2 Assets font.

So, I'll replace this font with XAML based vector icon.
Please wait for a while.

**Comment by sourcechord** [comment]
I've fixed this issue, and released [FluentWPF v0.4.1](https://github.com/sourcechord/FluentWPF/releases/tag/v0.4.1)
