### ISSUE TITLE
Pointertracker affects nearby controls

### ISSUE THREAD

**Issue by Symbai** [sourcechord/FluentWPF#27]
Downloaded project with commits as of now. Changed reveal brush to red to make it more visible. As you can see hovering over the button also affects the textbox but it shouldn't.

![a](https://user-images.githubusercontent.com/14368203/47289844-2be18c00-d5ec-11e8-8b34-e8791ecdd2ed.gif)

**Comment by fangeles02** [comment]
I've created a workaround for this:

Create a new style based on ButtonRevealStyle which can be found here: https://github.com/sourcechord/FluentWPF/blob/master/FluentWPF/Styles/Button.xaml

_(You may copy paste the code to find where the code is located)_


For the BackgroundColor, change the the color of the hoverLight from white to your desired color:
` <Border x:Name="hoverLight" Background="{local:RevealBrush Color=White, Size = 250,Opacity=0.6}" />`

Same with the BorderBrush
`<!-- MouseOver border -->`
                        `<Border x:Name="border"
                                BorderBrush="{local:RevealBrush Color=White,Size=120,Opacity=0.5}"`
                               ` BorderThickness="{TemplateBinding BorderThickness}">`
                        `</Border>`

Use that style for the button
`<Button Content="Sample"  Style="{StaticResource MyCustom_ButtonRevealStyle}" />`

Will give you this sample output:
![ezgif-5-fb0257bb8fc1](https://user-images.githubusercontent.com/26376969/47328410-9dc8dc80-d6a3-11e8-8ac1-28cb83b2bbb4.gif)


Hope this helps :)

**Comment by sourcechord** [comment]
Hi, @Symbai.
I think @fangeles02's answer is suitable in this case.
Please try it.

If you couldn't resolve, please show me your code in this issue.
