### ISSUE TITLE
TextBoxRevealStyle with Placeholder

### ISSUE THREAD

**Issue by fangeles02** [sourcechord/FluentWPF#28]
I've created a textbox control based on the original textbox and added a placeholder property in it.

![textbox_holder](https://user-images.githubusercontent.com/26376969/47569113-6b4e0680-d965-11e8-830c-53c198b701d8.gif)

Sample usage:
`<fw:FluentTextBox  PlaceHolder="Enter anything" Padding="5"  Margin="5" Width="120" HorizontalAlignment="Left"/>`

I wonder if I can contribute this one (and future fluent-based controls) to this project.

Thanks.
:)

**Comment by sourcechord** [comment]
Hi, fangeles02.

Sorry for replying so very late.
I'm grateful for your kind offer.Ofcause, PR is very welcome.

UWP's TextBox has Placeholder property, but WPF's doesn't.
I understood that feature is needed.

I'm reviewing your PR, and will write comment on that PR page when I finish review.

**Comment by fangeles02** [comment]
Thanks, I will try to create more custom fluent-based controls :)

**Comment by sourcechord** [comment]
resolved #35
