### ISSUE TITLE
Force Light or Dark System Theme

### ISSUE THREAD

**Issue by andrew-mi** [sourcechord/FluentWPF#29]
@sourcechord Hi, is there any way to force FluentWPF to use a light or dark theme?
Is it possible to force FluentWPF to pretend that the user set the 'App mode' switch in settings to, say, dark?

I have tried swapping out my App.xaml reference `<ResourceDictionary Source="pack://application:,,,/FluentWPF;component/Styles/Controls.xaml" />` for `.../Styles/Colors.Dark.xaml`
This correctly changed the color of the window title (ie 'MainPage' or whatever); but doesn't swap out the window control buttons in the top right corner for the appropriate theme. See Picture: 
![image](https://user-images.githubusercontent.com/20514615/47613016-803fac80-dac1-11e8-92b0-c5908756dc57.png)

`SourceChord.FluentWPF.SystemTheme.Theme` (which I think is what I am trying to change for this effect) can't be set. Is something like this currently possible with this library?

Similar Issue: #1 (Closed with no solution)

Thanks in Advance,
Andrew Mitchell

**Comment by sourcechord** [comment]
Hi, @andrew-mi.

There is `ResourceDictionaryEx.GlobalTheme` property to determine the application's theme.
(Sorry for lack of documentation.)

You can force FluentWPF to use arbitrary theme with below code.
```cs
    public partial class App : Application
    {
        public App()
        {
            SourceChord.FluentWPF.ResourceDictionaryEx.GlobalTheme = SourceChord.FluentWPF.ElementTheme.Dark;
        }
    }
```
Please try it.

**Comment by fangeles02** [comment]
I've also found a bug on the control buttons, if based on the actual system theme, the foreground of the close button remains black. Please images below.

_OK on inactive window_
![acrylic 1](https://user-images.githubusercontent.com/26376969/47688238-54d2d400-dc1f-11e8-9438-77fc078d7be8.PNG)

_Close button remains black when active_
![acrylic 2](https://user-images.githubusercontent.com/26376969/47688247-5b614b80-dc1f-11e8-9fb0-95b371a2afba.PNG)

**Comment by andrew-mi** [comment]
> Hi, @andrew-mi.
> 
> There is `ResourceDictionaryEx.GlobalTheme` property to determine the application's theme.
> (Sorry for lack of documentation.)
> 
> You can force FluentWPF to use arbitrary theme with below code.
> 
> ```cs
>     public partial class App : Application
>     {
>         public App()
>         {
>             SourceChord.FluentWPF.ResourceDictionaryEx.GlobalTheme = SourceChord.FluentWPF.ElementTheme.Dark;
>         }
>     }
> ```
> 
> Please try it.

Thanks for the reply. I will try it later today (and close issue if you don't first) when I have my machine and can confirm it works.
Thanks for the amazing library, Andrew Mitchell

**Comment by andrew-mi** [comment]
Thanks again for the fix, it worked amazing.

**Comment by sourcechord** [comment]
Thanks @fangeles02.

I can reproduce it.
It seems that AcrylicWindow's close button doesn't follow system theme change.
I'll fix it in the next release(or in the near future).
