### ISSUE TITLE
A window with  AcrylicWindow.Enabled="True" cannot be snapped (multitask) in windows 10 tablet mode

### ISSUE THREAD

**Issue by tzurp** [sourcechord/FluentWPF#34]
The result is that in tablet mode you can't put your app with AcrylicWindow.Enabled side by side with other apps. There is no problem when the feature is off.

**Comment by sourcechord** [comment]
Hi, @tzurp.
I couldn't reproduce it.
Could you tell me more information?

**Comment by tzurp** [comment]
You must test it with touch screen device in Tablet mode

**Comment by sourcechord** [comment]
I'm glad to here that 😄 
Thanks.
