### ISSUE TITLE
#Bug. When using two monitors, the window goes to the second screen.

### ISSUE THREAD

**Issue by AndreyGrishin** [sourcechord/FluentWPF#36]
When using two monitors, the window goes to the second screen. When you turn on the Acrylic effect

https://a.icons8.com/pNoVVVlQ/lkL8Uu/2018-12-27_17-40-47.png

Any idea how to fix this?

**Comment by sourcechord** [comment]
Hi, @AndreyGrishin.
Thanks for the feedback 😄 

I recognized this issue.
I'm trying to fix this issue, but it is difficult.
Please wait for a while.

**Comment by AndreyGrishin** [comment]
Thanks for the help

**Comment by Stryxus** [comment]
I am seeing this in a different way. Its quite odd.

https://cdn.discordapp.com/attachments/530128620732022811/530128652915179523/unknown.png

**Comment by sourcechord** [comment]
Hi @AndreyGrishin, @Stryxus 
It took a long time, but finally I was able to fix it.
I fixed it in [FluentWPF 0.10.0-alpha001](https://github.com/sourcechord/FluentWPF/releases/tag/0.10.0-alpha001): this is pre-release packages.
I'm confirming this way in several environments. If there is no issues, I'll release it as FluentWPF 0.10.0.
Please wait for a while.

**Comment by sourcechord** [comment]
It was supported in FluentWPF 0.10.0.
I'll close this issue. If there are any problems, please reopen this issue.
