### ISSUE TITLE
Titlebar cropped when maximized

### ISSUE THREAD

**Issue by HelgeKeck** [sourcechord/FluentWPF#38]
When maximizing a window, the titlebar is cropped on the top side. doesnt look nice and isnt touch friendly

**Comment by Goose-Bomb** [comment]
goto **FluentWPF/Themes/Generic.xaml** , line 28,
add these into the Window Maximized DataTrigger

``` xaml
<DataTrigger Binding="{Binding WindowState, RelativeSource={RelativeSource Self}}" Value="Maximized">
    <Setter TargetName="windowBorder" Property="MaxWidth" Value="{Binding Source={x:Static SystemParameters.WorkArea}, Path=Width}" />
    <Setter TargetName="windowBorder" Property="MaxHeight" Value="{Binding Source={x:Static SystemParameters.WorkArea}, Path=Height}" />
    <Setter TargetName="windowBorder" Property="Border.BorderThickness" Value="0"/>
</DataTrigger>
```
this should work

**Comment by sourcechord** [comment]
Sorry for responding so late.
I fixed this issue, and release as FluentWPF 0.7.0 soon.
Please wait for a while.

**Comment by JohnLouderback** [comment]
@sourcechord  I am still experiencing this issue.

**Comment by astef** [comment]
Just wanted you guys to know there's a bug in `SystemParameters.WindowResizeBorderThickness`, I have described and fixed it here: https://stackoverflow.com/questions/2967218/window-out-of-the-screen-when-maximized-using-wpf-shell-integration-library/61299269#61299269
