### ISSUE TITLE
.Net core 3 WPF uspport

### ISSUE THREAD

**Issue by RyoukoKonpaku** [sourcechord/FluentWPF#39]
With .NET core 3.0.0 supporting WPF. Targeting FluentWPF library to support it would be nice as we can get all the improvements of .Net core while using WPF. 

I managed to convert the project to core 3.0 without much problems on my fork. Just needed to add `System.Management` from `Windows.Compatability` from nuget. I think it'd be a great addition to target.

**Comment by sourcechord** [comment]
Hi, @RyoukoKonpaku
Sorry for responding so late.
Thanks for the feedback 😄 

I'd like to support .NET Core3.
But now, I'm not very familiar with .NET Core3, and learning how to use it.

I recognized that supporting .NET Core3 is worthwhile.
I'll try to support it in the future update.

Please wait for a while.

**Comment by Mohsens22** [comment]
@RyoukoKonpaku @sourcechord 
Hello, I have seen this issue and I decided to support native Core3.0 for this library. The fact is that you can use current nuget for the project, it might work but problem is that your app will be .NET framework dependent as well as nercore runtime, while netcore 3.0 can be exported "Self Contained" and current package can't let that happen so Visual Studio complains about that.

 [Here is my pull request fixing the issue](https://github.com/sourcechord/FluentWPF/pull/57)

I added another project targeting Netcore 3 and I referenced the netcore sample to that. You can publish that library under the name of FluentWPF.Core (or you can multi-target your current package".

I published my own package of this pull request as [FluentWPF.Core.Alpha](https://www.nuget.org/packages/FluentWPF.Core.Alpha/) and I used it in a project so I confirm that it works perfectly.

**Comment by sourcechord** [comment]
Hi, @Mohsens22
I published FluentWPF0.8.0-alpha.
It contains both .NET framework and .NET Core libraries.
But, it have not tested enough, so that I released FluentWPF0.8.0-alpha as nuget pre-release package.
I'll publish it as stable release within a few weeks.

**Comment by sourcechord** [comment]
It is fully supported from FluentWPF 0.8.0.
Now, FluentWPF has both .NET Framework and .NET Core assemblies.
