### ISSUE TITLE
Binding error message on the Output window in Visual Studio

### ISSUE THREAD

**Issue by joao7yt** [sourcechord/FluentWPF#44]
`System.Windows.Data Error: 40 : BindingExpression path error: 'ExtendViewIntoTitleBar' property not found on 'object' ''MainWindow' (Name='Window')'. BindingExpression:Path=ExtendViewIntoTitleBar; DataItem='MainWindow' (Name='Window'); target element is 'ContentPresenter' (Name=''); target property is 'NoTarget' (type 'Object')`

Probably caused by [line 280 in Window.xaml](https://github.com/sourcechord/FluentWPF/blob/master/FluentWPF/Styles/Window.xaml#L280)

Downloaded project and this was accused:
![Sem título](https://user-images.githubusercontent.com/10665193/57146873-c0e3ef80-6d9c-11e9-9576-7d89eba14bdf.png)

**Comment by sourcechord** [comment]
Hi @joao7yt

Sorry for responding so late, and thanks for the feedback.
Now, FluentWPF has some binding errors in AcrylicWindow.
I'm trying to get rid of it.

I'll fix it in next release.
Please wait for a while.

**Comment by joao7yt** [comment]
Fine, thanks

**Comment by sourcechord** [comment]
Hi, @joao7yt 
It was fixed in FluentWPF 0.8.0, and I'll close this issue.
If you have any problems, please reopen this issue.
