### ISSUE TITLE
How to change the Reveal highlight color?

### ISSUE THREAD

**Issue by ImminentFate** [sourcechord/FluentWPF#45]
In the Readme file, the Calculator demo shows that some of the buttons have a blue reveal highlight color, but I can't work out how to go about setting this. 

Thanks :) 

Edit:
Worked it out for anyone else interested, it's not exposed directly; you need to change the following:
https://github.com/sourcechord/FluentWPF/blob/8ba57629fcefcb9652bb28e97ff5333bb9a81a41/FluentWPF/Styles/Button.xaml#L328-L333

to 

```xml
             <ControlTemplate.Triggers>
                <Trigger Property="IsMouseOver" Value="True">
                    <Setter TargetName="root" Property="Background">
                        <Setter.Value>
                            <SolidColorBrush Color="{Binding ButtonBackground.Color}" Opacity="0.8" />
                        </Setter.Value>
                    </Setter>
                </Trigger>
            </ControlTemplate.Triggers>

```

**Comment by sourcechord** [comment]
Hi, @ImminentFate
Sorry for responding so late.

FluentWPF has two styles for Button control.(ButtonRevealStyle/ButtonAccentRevealStyle)
But, there is no property to customize the color when you move the mouse over the button.

I'd like to consider customizing hover color for Buttons.

**Comment by sourcechord** [comment]
It is supported from [FluentWPF 0.8.0](https://github.com/sourcechord/FluentWPF/releases/tag/v0.8.0).
I'll close this issue.
If you have any problems, please reopen this issue.
