### ISSUE TITLE
Windows 1903 Light Theme

### ISSUE THREAD

**Issue by poochie89** [sourcechord/FluentWPF#47]
Windows 10 introduced a light theme for the Startmenu, Taskbar etc.
Would be great if we could get these colors from the AccentColors

**Comment by sourcechord** [comment]
Hi, @poochie89 
Sorry for responding so late.
Thanks for the feedback.

It is good idea!
I'll add these feature in future update.
Please wait for a while.

**Comment by sourcechord** [comment]
It is supported from [FluentWPF 0.8.0](https://github.com/sourcechord/FluentWPF/releases/tag/v0.8.0).
I'll close this issue.
