### ISSUE TITLE
Title text and buttons become transparent when changing system accent color

### ISSUE THREAD

**Issue by shoker537** [sourcechord/FluentWPF#50]
If the app is launched and you change system accent color (Win10 1809), the title objects become transparent.
![image](https://user-images.githubusercontent.com/17161332/58505215-21483000-8195-11e9-87a0-d4f41f8cd9a1.png)

**Comment by sourcechord** [comment]
Hi, @shoker537 
Sorry for responding so late.
I coundn't reproduce this issue.
Please tell me more information 🙏

**Comment by shoker537** [comment]
Hi, @sourcechord 
I just realized when this is happening: If you use code-behind AcrylicWindow (without using XAML) - it disappears.
When I have found this bug it was another version of FluentWPF and the whole titlebar disappeared.
Now in 0.7.0 it is like this: https://i.imgur.com/8rLdDcT.png (some buttons are still on the screen)
And when I was checking it in 0.7.0, the first try I wasn't need to change the system color - I just opened the Color settings in Windows and it disappeared. Next try I was need to change the color to see it disappeared.

**Comment by sourcechord** [comment]
Hi, @shoker537

Thanks for the information.
I tried to create AcrylicWindow by C# code.
But, it shown correctly.

I tested by below code.
```cs
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            var win = new AcrylicWindow();
            win.Show();
        }
    }
```

Therefore, I couldn't still reproduce this issue.
Could you attach sample code to here?

**Comment by shoker537** [comment]
@sourcechord I mean a way to create the project without xaml:
remove all default .cs files, create Application.cs with code
`    public class Application
    {
        [STAThread]
        public static void Main(string[] args)
        {
            System.Windows.Application app = new System.Windows.Application();
            app.Run(new MainWindow());
        }
    }`
So here u can see new MainWindow() - it is a custom AcrylicWindow class.
I created that project this way.

**Comment by sourcechord** [comment]
@shoker537
You mean you wrote following codes?
```cs
    public class Application
    {
        [STAThread]
        public static void Main(string[] args)
        {
            System.Windows.Application app = new System.Windows.Application();
            app.Run(new MainWindow());
        }
    }

    public class MainWindow : AcrylicWindow
    {
    }
```

I tried these code, but it shows AcrylicWindow correctly.(in Windows10 1903)
I uploaded these codes to the following repository.
https://github.com/sourcechord/FluentWPF_test1


By the way, these App.xaml less codes doesn't supported by FluentWPF.
Because FluentWPF needs to initialize ResourceDictionaries in App.xaml.(See also [preparation](https://github.com/sourcechord/FluentWPF#preparation))

If you remove app.xaml, FluentWPF can't find resources and can't apply required styles.

**Comment by shoker537** [comment]
@sourcechord Yes, this code. 
It is possible to add ResourceDictionaries code-behind.
For ex. like this in AcrylicWindow class initializing:
```c#
public MainWindow(){
ResourceDictionary rd = new ResourceDictionary();
            var fw = new ResourceDictionary()
                {Source = new Uri("pack://application:,,,/FluentWPF;component/Styles/Controls.xaml")};
            this.Resources.MergedDictionaries.Add(fw);
}
```
It initializes fine and all controls work fine, but not the title.

Okay, got it, seems like there is something in title that requires xaml.

**Comment by sourcechord** [comment]
@shoker537 

I tried above code in Windows10 1809.
But, I couldn't reproduce it.
I suspect that reported issue is caused by MainWindow's definition.
Please tell me settings of MainWindow.

What property are you set to MainWindow?

**Comment by shoker537** [comment]
@sourcechord 
I set to MainWindow:

```c#
WindowStartupLocation = System.Windows.WindowStartupLocation.CenterScreen;
TintColor = Color.FromArgb(130, 0, 30, 101);

Background = new SolidColorBrush(Color.FromArgb(0, 0, 0, 0));
Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
BorderThickness = new Thickness(1, 1, 1, 1);
BorderBrush = new SolidColorBrush(Color.FromArgb(70, (byte) 0, (byte) 70, (byte) 255));
Width = 1100;
Height = 550;
ResizeMode = ResizeMode.CanMinimize;
Title = "Title text";
```

**Comment by sourcechord** [comment]
@shoker537 
Thanks for the information 😃 
I became to reproduce it.

And I found the cause of this issue.
You set ResourceDictionary to MainWindow object, but System.Windows.Application needs to be initialized with the RecourceDictionaly.

Please try the following code.
```cs
    public class Application
    {
        [STAThread]
        public static void Main(string[] args)
        {
            var app = new System.Windows.Application();

            var fw = new ResourceDictionary()
            {
                Source = new Uri("pack://application:,,,/FluentWPF;component/Styles/Controls.xaml")
            };
            app.Resources.MergedDictionaries.Add(fw);

            app.Run(new MainWindow());
        }
    }

    public class MainWindow : AcrylicWindow
    {
        public MainWindow()
        {
            WindowStartupLocation = WindowStartupLocation.CenterScreen;
            TintColor = Color.FromArgb(130, 0, 30, 101);

            Background = new SolidColorBrush(Color.FromArgb(0, 0, 0, 0));
            Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
            BorderThickness = new Thickness(1, 1, 1, 1);
            BorderBrush = new SolidColorBrush(Color.FromArgb(70, (byte)0, (byte)70, (byte)255));
            Width = 1100;
            Height = 550;
            ResizeMode = ResizeMode.CanMinimize;
            Title = "Title text";
        }
    }
```

**Comment by shoker537** [comment]
@sourcechord 
Yay! Thank you a lot for helping!

It works great now. Thank you for your work!

**Comment by sourcechord** [comment]
I'm glad to here that.
