### ISSUE TITLE
Gaussian Blur effect is much weaker in version 0.7.0

### ISSUE THREAD

**Issue by ashelleyPurdue** [sourcechord/FluentWPF#51]
The official Acrylic effect has a much stronger gaussian blur than the latest version of FluentWPF.

**Comment by noobhacker** [comment]
I downgraded to 0.6.1 to fix this issue. There might be some new APIs coming in to 1903 and the shifting is in unstable state.

Source from author:
http://sourcechord.hatenablog.com/entry/2019/05/17/235928
http://sourcechord.hatenablog.com/entry/2019/06/02/172120

**Comment by sourcechord** [comment]
Hi, @ashelleyPurdue
Sorry for responding so late..

This is current limitation of FluentWPF on Windows10 1903.
(see also https://github.com/sourcechord/FluentWPF/issues/42#issuecomment-493407364 #49)

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
