### ISSUE TITLE
TitleBar property doesn't work when using AcrylicWindow.Enabled attached property

### ISSUE THREAD

**Issue by tim-fernico** [sourcechord/FluentWPF#54]
I am using the AcrylicWindow TitleBar property after upgrading to 0.7 to get the 1903 fix. However, it doesn't work if you enable the AcrylicWindow using the AcrylicWindow.Enabled attached property.

**Comment by sourcechord** [comment]
Hi, @tim-fernico.
I fixed this issue, and released as FluentWPF 0.8.0-alpha003
Please, try it.
