### ISSUE TITLE
Blur offset when using SizeToContent="WidthAndHeight" in AcrylicWindow

### ISSUE THREAD

**Issue by BeautyRazor** [sourcechord/FluentWPF#56]
![изображение](https://user-images.githubusercontent.com/2052851/60473412-bbf4cc80-9c75-11e9-8bb1-175f91ac858c.png)

**Comment by Barina** [comment]
Same here. can't find a workaround.
It also not rendering properly at first. after resizing it renders the whole window/control.
![Issue](https://user-images.githubusercontent.com/370379/60638264-55fb7700-9e26-11e9-89d7-9e59412999c3.jpg)
![Expected](https://user-images.githubusercontent.com/370379/60638265-56940d80-9e26-11e9-8010-5c396ef170d0.jpg)

**Comment by sourcechord** [comment]
Hi @BeautyRazor @Barina

Thanks for the feedback.
I recognized this issue.

But it is little a bit difficult to fix.
I'll try to fix it in future update.

**Comment by sourcechord** [comment]
This is famous bug in WPF.
When use WindowChrome with `SizeToContent="WidthAndHeight"`, WPF can't calculate the exact window size.

```xml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        SizeToContent="WidthAndHeight"
        Title="MainWindow">
    <WindowChrome.WindowChrome>
        <WindowChrome GlassFrameThickness="-1"/>
    </WindowChrome.WindowChrome>
    <Grid Background="Beige" Width="300" Height="200">
        <TextBlock Margin="10"
                   HorizontalAlignment="Left"
                   VerticalAlignment="Top"
                   Text="TextBlock"
                   TextWrapping="Wrap" />
    </Grid>
</Window>
```
![image](https://user-images.githubusercontent.com/14825436/64057475-39867b80-cbd8-11e9-8939-19565d198d7a.png)


But I found a workaround for it.
The way is to call InvalidateMeasure method in OnContentRendered.

```cs
        protected override void OnContentRendered(EventArgs e)
        {
            base.OnContentRendered(e);

            if (this.SizeToContent != SizeToContent.Manual)
            {
                this.InvalidateMeasure();
            }
        }
```

In addition, it can be emmbeded in AcrylicWindow's implement.
So that, I'll try to fix it in next FluentWPF update.
