### ISSUE TITLE
Out of the box errors

### ISSUE THREAD

**Issue by matthewsheeran** [sourcechord/FluentWPF#6]
Out of the box on the following line in the Sample:
            SystemTheme.ThemeChanged += SystemTheme_ThemeChanged;

'FluentWPFSample.exe' (CLR v4.0.30319: FluentWPFSample.exe): Loaded 'C:\Users\Matthew\Desktop\Fluent Design System\FluentWPF\FluentWPF-master\Sample\FluentWPFSample\bin\Debug\FluentWPF.dll'. Symbols loaded.
Exception thrown: 'System.NullReferenceException' in FluentWPF.dll
Exception thrown: 'System.TypeInitializationException' in FluentWPF.dll
An exception of type 'System.TypeInitializationException' occurred in FluentWPF.dll but was not handled in user code
The type initializer for 'SourceChord.FluentWPF.SystemTheme' threw an exception.

Out of the box on finding the Controls.xaml in my own WPF Sample using FluentWPF from NuGet:
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/FluentWPF;component/Styles/Controls.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

An error occurred while finding the resource dictionary "pack://application:,,,/FluentWPF;component/Styles/Controls.xaml".

Guess I am going back to Mahapps since something is definitively not up to scratch here for a VS2017 OOTB FluentWPF experience to even consider further exploration let alone actual use..

**Comment by sourcechord** [comment]
Hi, @matthewsheeran.
Thanks for your feedback.

So, I'm afraid I can't reproduce the error you're seeing.
Could you tell me your environment(OS, .net framework version, and so on.)?

I implemented theme reactive feature in FluentWPF 0.3.0.
(I'm developing FluentWPF with Windows10 PC)
But, these feature might cause bad side-effect in Windows7.

**Comment by jt-85** [comment]
Hi, sourcechord
Thanks for your working, good library.  
I have got a similar error like @matthewsheeran.
It occurs on the version 0.3.0. 
0.2.2 is working good. 
I'm working with Windows10 PC

**Comment by pcruzehrez** [comment]
I was able to locate the error. In SystemTheme.cs, line 53:
`var intValue = (int)regkey.GetValue("AppsUseLightTheme");`

The error happens when that actual value does NOT exist in the registry and there's no fallback value (i.e. darktheme).

**Comment by sourcechord** [comment]
Hi, @pcruzehrez
Thanks for your information.
Existence of `AppsUseLightTheme` is checked in SystemTheme.cs, [line 51](https://github.com/sourcechord/FluentWPF/blob/master/FluentWPF/Resources/SystemTheme.cs#L51)
`if (regkey == null) return ApplicationTheme.Light;`

The crash is caused by AccentColors class.

[These method](https://github.com/sourcechord/FluentWPF/blob/master/FluentWPF/Resources/AccentColors.cs#L52-L54) can't invoke in Windows 7.
And I've fixed this issue in FluentWPF v0.3.1 
Please, try it.
