### ISSUE TITLE
brushes.xaml missing from v0.8.0

### ISSUE THREAD

**Issue by stevenbrix** [sourcechord/FluentWPF#61]
I just pulled down v0.8.0 from nuget and it looks like brushes.xaml is missing, so the app crashes when i try to use FluentWPF

**Comment by sourcechord** [comment]
Hi, @stevenbrix

Thanks for the feedback 😃 
FluentWPF0.8.0-alpha.nupkg contains both net45 and netcoreapp3.0 assemblies.
But, I set netcoreapp3.0 binary as net45 assembly by mistake.

This has been fixed and released as FluentWPF0.8.0-alpha002.
Please try it.

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
