### ISSUE TITLE
How to apply fw:AcrylicBrush grid to Border background

### ISSUE THREAD

**Issue by Altiano** [sourcechord/FluentWPF#7]
How to apply fw:AcrylicBrush grid to Border background.

This won't work:
 `   Background="{fw:AcrylicBrush grid}"`

**Comment by sourcechord** [comment]
Hi, @Altiano.
Thanks, for feedback!!

AcrylicBrush blurs only target UIElement.
(`Background="{fw:AcrylicBrush grid}"` means that AcrylicBrush uses target control(named `grid`) as background layer)
If `grid` is transparent, AcrylicBrush becomes transparent, too.
Please, check the brush of `grid` control.

**Comment by Altiano** [comment]
is it target the `name` property (`name="grid"`) of element or the element type itself (`<Grid />`) ?

**Comment by marcpabst** [comment]
It's the name of the elment. `<Grid Name="grid"/>`

**Comment by sourcechord** [comment]
Hi, @Altiano.
Thanks, @marcpabst.

Sorry for replying so late.
`"{fw:AcrylicBrush grid}"`means `"{fw:AcrylicBrush TargetName=grid}"`.
It is shorthand syntax for AcrylicBrush markup extension.
`TargetName` indicates target element's x:Name attribute, just as marcpabst say.

**Comment by xperiandri** [comment]
The issue is that `AcrylicBrush` is applied only if the element width and height explicitly set.
Otherwise (auto-size, binding) it does not work

**Comment by xperiandri** [comment]
@sourcechord
