### ISSUE TITLE
Incorrect behaviour with SizeToContent

### ISSUE THREAD

**Issue by m1024** [sourcechord/FluentWPF#70]
Incorrect behaviour with window property SizeToContent = "WidthAndHeight"
![SizeToContent](https://user-images.githubusercontent.com/5684734/64625808-7aab3680-d3f5-11e9-9f29-1b9c431cabd7.JPG)

**Comment by m1024** [comment]
Workaround: 
window.ContentRendered += (o, args) => window.BorderThickness = new Thickness(1);

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
