### ISSUE TITLE
Suggestion: Update accent colors when they changed.

### ISSUE THREAD

**Issue by Barina** [sourcechord/FluentWPF#71]
Currently the color stays the same when the accent colors of Windows changes.
It'll be great to set them to update automatically when Windows changes the colors or maybe have an option to get notified when it is changed and do some code manually.

I previously used SystemParameters.WindowGlassColor for that witch seems to automatically change the color but it's only one color..
We can multiply with different highlight color values (as follows) but I think it'll be a nice feature to have in Fluent WPF.

`Color multipliedColor = Color.Multiply(SystemParameters.WindowGlassColor, 10);`

**Comment by sourcechord** [comment]
Hi, @Barina

Sorry for responding so late.
FluentWPF has `AccentColors.ImmersiveSystemAccentBrush` properties for using system accent colors.
Please try `AccentColors.ImmersiveSystemAccentBrush` instead of `SystemParameters.WindowGlassColor`.

**Comment by Barina** [comment]
Does these `fw:AccentColors.ImmersiveSystemAccent`s automatically changed when Windows accent color changes?
Maybe I missed something with the binding

BTW I am using FW AccentColors..

**Comment by Armin2208** [comment]
{Binding Path=(fw:AccentColors.ImmersiveSystemAccentBrush)}

**Comment by sourcechord** [comment]
`fw:AccentColors.ImmersiveSystemAccent` follows Windows accent color changes.
I'll close this issue.
If there are any problems, please reopen this issue.
