### ISSUE TITLE
.Net Core 3.0 Support

### ISSUE THREAD

**Issue by DHitchenUK** [sourcechord/FluentWPF#72]
Currently getting compiler errors when using this with a .Net Core 3.0 WPF project; it says this package may not be comatible.

**Comment by sourcechord** [comment]
Hi, @DHitchenUK

Sorry for responding so late.
.NET Core3.0 support is inprogress in FluentWPF 0.8.0-alpha
See also #39

Please wait for a while.

**Comment by DHitchenUK** [comment]
Thanks, I use this in one of my projects, i also use another one in my main project and to show gratitude I donate (amazon wish list) to them.. you might want to add that to your project description if you're intersted, here's their example..

Donate
If you have an uncontrollable urge to give me something for the time and effort I am putting into this project then please buy me something from my amazon wish list or send me an amazon gift card. If you prefer to use PayPal then click here.

**Comment by sourcechord** [comment]
Thanks for your kind offer!
But, I didn't create Amazon's wish list, and don't have PayPal acount.
I really appriciate your thought but you don't have to. Thank you so much 😄 

By the way, I'm now considering to participate in GitHub sponsors progam.
I might introduce it into FluentWPF in future.
