### ISSUE TITLE
NRE on init when trying show MessageBox

### ISSUE THREAD

**Issue by AntonKosenkoDX** [sourcechord/FluentWPF#73]
When I trying call MessageBox.Show() in Application.OnStartup event handler, I got NRE with callstack:
![изображение](https://user-images.githubusercontent.com/2052851/66272300-9bd63a00-e870-11e9-9c6b-6cc61dc7a9a2.png)

**Comment by sourcechord** [comment]
Hi, @BeautyRazor
Thanks for the feedback.

I can reproduce it.
I'm trying to fix it.
Please wait for a while.

**Comment by sourcechord** [comment]
Hi, @AntonKosenkoDX 
Sorry for responding so late.
It was fixed in FluentWPF 0.10.0.
I'll close this issue. If there are any problems, please reopen this issue.
