### ISSUE TITLE
Parallax view

### ISSUE THREAD

**Issue by innuendo33** [sourcechord/FluentWPF#75]
Hi Minami 

Not an issue but I was wondering  if it is possible to add such effect in windows visual styles and how to if you get an idea to mod mstyles or shellstyle files ? 

Great work . 

Regards

**Comment by sourcechord** [comment]
Hi, @innuendo33

FluentWPF is based on WPF framework.
WPF is not intended to customize system shell, and is not suitable for it.
So that, FluentWPF is not suitable for it too.

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
