### ISSUE TITLE
Windows Defender detects FluentWPF.dll as virus

### ISSUE THREAD

**Issue by Armin2208** [sourcechord/FluentWPF#79]
Windows Defender thinks FluentWPF.dll is a virus since release 0.8.0. I updated the nuget package yesterday. But the notification appeared today. Maybe because of automatic quick scan in background.

It says the behaviour of the software is potentially unwanted. 

![image](https://user-images.githubusercontent.com/32982430/68544726-8ea7f000-03c6-11ea-87e7-a8317389b10b.png)

**Comment by sourcechord** [comment]
Hi, @Armin2208 
Thanks for the feedback.

I'm using Kaspersky Internet Security, and it doesn't detect any threats.
I think it could be misdetection in Windows Defender.
![image](https://user-images.githubusercontent.com/14825436/68593600-2990ef00-04d9-11ea-9b7a-1baa2f307ab7.png)


I'll check it with Windows Defender later.
But I'm busy with work this week.
I'll check it in this weekend.
Please wait for a while.

I am sorry for the inconvenience.

**Comment by sourcechord** [comment]
Hi, @Armin2208

I tried to scan [FlluentWPF0.8.0](https://www.nuget.org/packages/FluentWPF/0.8.0) with Windows Defender, but any threats were not detected.
Is Windows Defender still detecting any threats in your environment?

**Comment by Armin2208** [comment]
Luckily you're right. Windows Defender doesn't recognize FluentWPF anymore as virus. Maybe someone at Microsoft checked this :)
Now again worry free, have a nice weekend <3

**Comment by sourcechord** [comment]
Thanks 😃 
I'm glad to hear that.

**Comment by Armin2208** [comment]
Wow mate, now I tested Auto Dark Mode with FluentWPF in the newest Insider-Preview in a virtual machine and this time not Defender itself detected FluentWPF.dll as bad software, but the new option to find potential unwanted software.

Good thing: Defender makes it clear that it isn't a real virus, it's more like: We think the program behaves in a way that you don't want. So no Red X, they use a yellow indicator.

Interesting change, I think with time this will also vanish.

![image](https://user-images.githubusercontent.com/32982430/69006816-10eb6380-0935-11ea-9af3-bea475a7a2e7.png)
