### ISSUE TITLE
can the library support windows 7

### ISSUE THREAD

**Issue by CougarsJ** [sourcechord/FluentWPF#8]
AccentColors seems only run in window 8 or later. It can not run in windows 7 system.should it  provide a default color setting or some kind styles to select  when in windows 7?

**Comment by sourcechord** [comment]
Hi, @CougarsJ.

Thanks feedback!!
FluentWPF 0.3.0 has bug in Windows 7.
AcrylicWindow crashes when runs on Windows 7, because that class uses AccentColors feature.

This is maybe same issue(#6)
Now, I am going to implement that switch AccentColors code depending on OS.
Please wait for a while.
