### ISSUE TITLE
Topmost window when deactivated background Transparent & Color

### ISSUE THREAD

**Issue by Proladon** [sourcechord/FluentWPF#81]
## Like GIF:
![0](https://user-images.githubusercontent.com/35193493/71776234-ecbd1200-2fc8-11ea-96a0-a9690e75f691.gif)

When Window deactivated, Acrylic effect will gone and turn to solid gray background.
it's possible to solute this?

**Comment by davidxuang** [comment]
As I know this is by-design. Native Fluent Design apps (UWP) such as the calculator behaves the same.

**Comment by Proladon** [comment]
> As I know this is by-design. Native Fluent Design apps (UWP) such as the calculator behaves the same.

yeah... i just saw same issues on stackoverflow. Thank for reply 👍

**Comment by sourcechord** [comment]
Hi, @Proladon 

It is by design.
BTW, there is `FallbackColor` property for modifying background colors when window is inactivated.
If you want to make transparent when window is deactivated, please try following code.

```xml
<Window x:Class="FluentWPFSample.Views.AcrylicWindow2"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:FluentWPFSample.Views"
        xmlns:fw="clr-namespace:SourceChord.FluentWPF;assembly=FluentWPF"
        mc:Ignorable="d"
        Title="AcrylicWindow2" Height="300" Width="300"
        fw:AcrylicWindow.Enabled="True"
        fw:AcrylicWindow.FallbackColor="Transparent">
    <Grid>
    </Grid>
</Window>
```
