### ISSUE TITLE
PasswordBox Extensions Problem

### ISSUE THREAD

**Issue by davidxuang** [sourcechord/FluentWPF#82]
```cs
<PasswordBox x:Name="Password" Margin="5" MaxLength="32"
             Style="{StaticResource PasswordBoxRevealStyle}"
             fw:Extensions.PlaceholderText="Password"/>
```

PlaceholderText is still visible when not empty but fade when it get focused.

System: Windows 10 64-bit 18363.592
Runtime: .NET Core 3.1.101

**Comment by sourcechord** [comment]
Hi, @davidxuang 

Thanks for the feedback.
I can reproduce it.
I'm trying to fix it, please wait for a while.
