### ISSUE TITLE
By playing the window animation,when moving the window,the ACCENT_ENABLE_ACRYLICBLURBEHIND Effect is Acceptable!

### ISSUE THREAD

**Issue by wuyang26** [sourcechord/FluentWPF#84]
In the theme xaml,like As follows:
            `  <Border.Resources>
                    <Storyboard x:Key="ImageFade" RepeatBehavior="Forever">
                        <DoubleAnimation Storyboard.TargetName="Title" Storyboard.TargetProperty="Opacity" 
                                         From="0.5" To="1" SpeedRatio="5">
                        </DoubleAnimation>
                    </Storyboard>
                </Border.Resources>`

then behind the code:
     when moving window:
               `  Border borderFrame = this.Template.FindName("PART_borderFrame", this) as Border;
                    Storyboard fadeAnimation = borderFrame.Resources["ImageFade"] as Storyboard;
                    fadeAnimation.Begin();`
     when stop moving:
               ` fadeAnimation.Stop();`

**Comment by sourcechord** [comment]
Hi @wuyang26

Thanks for your information.
It was interesting, but the laggy behavior still occurs when window is moving.
It is not acceptable 😔 

I'll continue to research for it.

**Comment by sourcechord** [comment]
I'll close this issue.
If you have any problems, please reopen this issue.
