### ISSUE TITLE
Image inside a Button with Fluent Design

### ISSUE THREAD

**Issue by Steffen-MLR** [sourcechord/FluentWPF#9]
```
<Button Grid.Row="1" Grid.Column="1" Name="btn_bugreport" Margin="5" Height="30" Style="{StaticResource ButtonRevealStyle}">
	<StackPanel>
		<Image Source="Resources/bug.png"/>
	</StackPanel>
</Button>
```

This snippet is inside my main grid, I want a button to show an picture for bugreport. (the Google Material Icon)
The Image shows in the Visual Studio Designer, but not during runtime. Did I miss something?

As a matter of effekt, I have more than one button. If I hover over one Button, all Buttons do hover animations (i think it is a shadow around the box). Is this normal? EDIT: Nevermind, my Buttons are next to each other, this is why i thought they react the same.

**Comment by sourcechord** [comment]
Hi, @Steffen-MLR.
Sorry for replying so late.
This is maybe due to the `StackPanel` that is implemented in Button's content.
You don't have to include `StackPanel` in Button's content.

Please try below code.
```xml
        <Button Grid.Row="1" Grid.Column="1"  Name="btn_bugreport" Margin="5" Height="30" Style="{StaticResource ButtonRevealStyle}">
            <Image Source="/Assets/Images/bug.png" />
        </Button>
```
