### ISSUE TITLE
Please update Dropdown/ComboBox Menu

### ISSUE THREAD

**Issue by Armin2208** [sourcechord/FluentWPF#92]
Hey, you seem busy because you don't update FluentWPF at the moment. But I still want to fill some issues  :)

ComboBox is a important and often used UI control that should be updated. Someone did made a implementation, but official support would be nice. 

Thanks.

**Comment by sourcechord** [comment]
Hi @Armin2208 

I released [FluentWPF0.9.0](https://github.com/sourcechord/FluentWPF/releases/tag/v0.9.0) that supports reveal styles for ComboBox.
Please try it 😄

**Comment by Armin2208** [comment]
love you! thanks!
