### ISSUE TITLE
Disabling Blur from Code

### ISSUE THREAD

**Issue by poochie89** [sourcechord/FluentWPF#94]
We can enable the blur by setting the attached property in code with
`AcrylicWindow.SetEnabled(this, true);`

After that, we unfortunately can not disable it again. Nothing happens wenn calling this method with false as paramter

**Comment by sourcechord** [comment]
Hi @poochie89 
Thanks for your feedback.This is same to #88, I'll close this issue.
If there are any problems, please reopen this issue.
