### ISSUE TITLE
Exceptions thrown when hovering over AcrylicPanel

### ISSUE THREAD

**Issue by Ydiren** [sourcechord/FluentWPF#95]
We are seeing lots of binding error exceptions thrown when hovering the mouse over elements of the AcrylicPanel.
Even thought the exceptions are all handled internally to FluentWPF (or handled by .Net itself) these exceptions are causing the application to slow down and stutter.

The fix for this problem is in #91 .

**Comment by sourcechord** [comment]
This is fixed in [FluentWPF 0.9.0](https://github.com/sourcechord/FluentWPF/releases/tag/v0.9.0).
So that, I'll close it.
